sudo: required
language: node_js
services:
  - docker

env:
  - $NODE_VERSION=8-alpine $DOCARYS_VERSION=$(npm show docarys version) $DOCARYS_SHORT_VERSION=${DOCARYS_VERSION:0:1}
  - $NODE_VERSION=9-alpine $DOCARYS_VERSION=$(npm show docarys version) $DOCARYS_SHORT_VERSION=${DOCARYS_VERSION:0:1} $LATEST=true

before_install:
  - docker pull node:$NODE_VERSION

script:
  - docker build -t docarys:latest . --build-arg NODE_VERSION=$NODE_VERSION  
  # - docker tag docarys:latest $DOCKER_USERNAME/docarys:$DOCARYS_SHORT_VERSION-$NODE_VERSION-build
  # - docker tag docarys:latest $DOCKER_USERNAME/docarys:$DOCARYS_VERSION-$NODE_VERSION-build
  # - docker images
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker push $DOCKER_USERNAME/docarys:$DOCARYS_SHORT_VERSION-$NODE_VERSION-build
  # - docker push $DOCKER_USERNAME/docarys:$DOCARYS_VERSION-$NODE_VERSION-build
  # - ./tag-latest.sh

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
