sudo: required
language: node_js
services:
  - docker

env:
  - $NODE_VERSION=8-alpine $DOCARYS_SHORT_VERSION=1 $DOCARYS_VERSION=1.1.0
  - $NODE_VERSION=9-alpine $DOCARYS_SHORT_VERSION=1 $DOCARYS_VERSION=1.1.0

jobs:
  include:
    - stage: Docker Build
      script:
      - ./build.sh
      - ./tag.sh
    - stage: Test
      script: 
      - docker run --rm $DOCKER_USERNAME/docarys:latest-build cat hello.txt
