sudo: required
language: node_js
services:
  - docker

env:
  - $NODE_VERSION=8-alpine $DOCARYS_VERSION=$(npm show docarys version) $DOCARYS_SHORT_VERSION=${DOCARYS_VERSION:0:1}
  - $NODE_VERSION=9-alpine $DOCARYS_VERSION=$(npm show docarys version) $DOCARYS_SHORT_VERSION=${DOCARYS_VERSION:0:1} $LATEST=true

before_install:
  - docker pull node:$NODE_VERSION

script:
  - docker build -t docarys:latest . --build-arg NODE_VERSION=$NODE_VERSION

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
