#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push $DOCKER_USERNAME/docarys:$DOCARYS_SHORT_VERSION-$NODE_VERSION-build
docker push $DOCKER_USERNAME/docarys:$DOCARYS_VERSION-$NODE_VERSION-build

if [ "$LATEST" = true ] 
then
    docker tag docarys:latest $DOCKER_USERNAME/docarys:latest-build
    docker push $DOCKER_USERNAME/docarys:latest-build
fi